name = "MachineLearningPotential"
uuid = "3c6de921-4f95-4537-8999-82f6d8a5f170"
authors = ["Gray Hunter"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
